//REFATORAR CAMPOS PARA QUE FIQUE CADA CAMPO EM UMA PAGE
//CASO FIQUE MUITO VAZIA A TELA COLOCAR IMG https://www.manypixels.co/gallery
//CRIAR UMA PAGINA NO FINAL COM UM RESUMÃO E USAR ELE PARA ENVIAR OS DADOS PARA O BANCO
//PAGE_CAMERA TERÁ QUE SER TELA FULL SCREEN
//ALGUM LOADING NO FINAL  